import localFont from "next/font/local";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "next-themes";
import NavbarCustom from "./components/navbar";
import { BusinessProvider } from "./providers/businessContext";

const vazir = localFont({
  src: "./fonts/Vazir-FD.woff2",
  display: "swap",
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "مدیران خودرو ایوبی یزد",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch داده‌ها (Static Data)
  const response = await fetch('https://namya.ir/api/v3/businesses/1165');
  const businessData = await response.json();

  return (
    <html dir="rtl" lang="fa-IR" suppressHydrationWarning>
      <body className={`${vazir.className} antialiased`}>
        <ThemeProvider>
          <NextUIProvider>
            <BusinessProvider value={businessData}>
              <NavbarCustom />
              <div className="overflow-hidden pt-2 md:pt-4">{children}</div>
            </BusinessProvider>
          </NextUIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
